GNN: true
TRA: false
analysis: false
autoreg_start: 10
blend: false
disp: true
epochs: 100
eval: false
exp_name: gnn_timeseries_baseline
extraction: false
gnn_num_layers: 5
gnn_width: 128
interpolate: false
mask: false
mask_bulk: false
merge: true
num_eval_cases: 20
seed: 123
temp: false
timeseries: true
tra_mlp_ratio: 2.0
tra_num_heads: 8
tra_num_layers: 5
tra_width: 128
train: true
visualization: false
vmstr: false
weight_decay: 0.001
