GNN: false
TRA: true
analysis: false
autoreg_start: 1
blend: false
disp: true
epochs: 500
eval: false
exp_name: tra_timeseries_sdf_layers_8_width_256_slices_64_wd_0p01_heads_8
extraction: false
gnn_num_layers: 5
gnn_width: 128
interpolate: true
mask: true
mask_bulk: false
merge: true
num_eval_cases: 50
restart_file: null
sdf: true
seed: 123
temp: false
timeseries: true
tra_mlp_ratio: 2.0
tra_num_heads: 8
tra_num_layers: 8
tra_num_slices: 64
tra_width: 256
train: true
visualization: false
vmstr: false
weight_decay: 0.01
