GNN: false
TRA: 3
analysis: false
autoreg_start: 1
blend: false
disp: true
epochs: 200
eval: false
exp_name: ts1
extraction: false
gnn_num_layers: 5
gnn_width: 128
interpolate: false
learning_rate: 0.0001
mask: true
mask_bulk: false
merge: true
num_eval_cases: 50
one_cycle_div_factor: 25
one_cycle_final_div_factor: 10000.0
one_cycle_pct_start: 0.3
one_cycle_three_phase: true
restart_file: null
schedule: null
sdf: true
seed: 123
temp: false
timeseries: true
tra_mlp_ratio: 2.0
tra_num_heads: 8
tra_num_layers: 8
tra_num_slices: 32
tra_width: 128
train: true
visualization: false
vmstr: false
weight_decay: 0.001
