act: gelu
batch_size: 1
dataset: elasticity
epochs: 500
eval: false
exclude: true
exp_name: CA_Elasticity
force_reload: false
gamma_init: 0.01
gamma_min: 0.0
gamma_schedule: constant
hidden_dim: 128
init_case: 0
init_step: 100
learning_rate: 0.001
max_cases: 10
max_steps: 500
mlp_ratio: 1.0
model_type: 3
noise_init: 0.1
noise_schedule: linear
num_heads: 8
num_layers: 8
num_slices: 64
one_cycle_div_factor: 25
one_cycle_final_div_factor: 4
one_cycle_pct_start: 0.05
one_cycle_three_phase: false
qk_norm: true
restart_file: null
schedule: CosineAnnealingLR
seed: 0
supernodes: 0
topk: 0
train: true
train_rollout_noise: 0.0
weight_decay: 0.0
