act: gelu
batch_size: 1
dataset: cylinder_flow
epochs: 500
eval: false
exp_name: 1_100c_300s
force_reload: false
gamma_init: 0.01
gamma_min: 0.0
gamma_schedule: constant
hidden_dim: 128
init_case: 0
init_step: 300
learning_rate: 0.001
max_cases: 100
max_steps: 300
mlp_ratio: 2.0
model_type: 1
noise_init: 0.1
noise_schedule: linear
num_heads: 8
num_layers: 5
num_slices: 64
one_cycle_div_factor: 25
one_cycle_final_div_factor: 40
one_cycle_pct_start: 0.1
one_cycle_three_phase: false
restart_file: null
schedule: CosineAnnealingLR
seed: 0
topk: 0
train: true
weight_decay: 1.0e-05
