act: gelu
batch_size: 1
dataset: cylinder_flow
epochs: 17
eval: false
exclude: false
exp_name: test_OG_1000train_100test_600s_17ep
force_reload: false
gamma_init: 0.01
gamma_min: 0.0
gamma_schedule: constant
hidden_dim: 128
init_case: 0
init_step: 0
learning_rate: 0.001
max_cases: 2
max_steps: 6
mlp_ratio: 1.0
model_type: 0
noise_init: 0.1
noise_schedule: linear
num_heads: 8
num_layers: 6
num_slices: 64
one_cycle_div_factor: 25
one_cycle_final_div_factor: 40
one_cycle_pct_start: 0.1
one_cycle_three_phase: false
qk_norm: false
restart_file: null
schedule: OneCycleLR
seed: 1
topk: 0
train: true
train_rollout_noise: 0.0
weight_decay: 1.0e-05
