GNN: true
TRA: false
autoreg_start: 10
blend: true
disp: true
epochs: 100
gnn_num_layers: 5
gnn_width: 96
interpolate: true
mask: true
mask_bulk: false
merge: true
name: vis_finaltime
num_eval_cases: 20
seed: 123
temp: false
tra_mlp_ratio: 2.0
tra_num_heads: 16
tra_num_layers: 5
tra_width: 192
train: true
vmstr: false
weight_decay: 0.0
